
import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "7789010028:AAEA5dC6R99-nHRR1KPlXCl74KvlTjTx6zo")
OWNER_ID = int(os.getenv("OWNER_ID", "7995588921"))

# 🔴 यही line missing है
MONGO_URL = os.getenv(
    "MONGO_URL",
    "mongodb+srv://h17589479_db_user:W5l1NuSQ2cak8I04@cluster0.tkxlnpf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
)

DB_NAME = "telegram_game"
SCORE_COLLECTION = "scores"
USER_COLLECTION = "users"
GROUP_COLLECTION = "groups"


STICKER = [
"CAACAgUAAxkBAAKV2Ge_HEejUGb8foZZ9eunAivt46rNAAL9EQAC-EXwV3yNmpSjijuwHgQ",
"CAACAgUAAxkBAAKV12e_HEUWk7Dr9lPFRy0YJ2W_aZQnAAIgEgACRnzxV6MUtKkl8-lcHgQ",
"CAACAgQAAxkBAAKV1me_HC0meq-fnc8-RrNQlkuvuddmAAKpFgACpvFxHgRaY3CLWAIXHgQ",
"CAACAgQAAxkBAAKV1We_HCp1JciP72U9NorWCvM9IvjSAAI9CQACzsTxUNSMpeZiwDESHgQ",
"CAACAgQAAxkBAAKV1Ge_HB5qp-1sh5Fih-RTyLJ34bljAAL6FgACpvFxHkyKzYENX-WBHgQ",
"CAACAgUAAxkBAAKV2We_HErZCR15-PcfUV3OEeNjsvMlAAITEAAC2ITwV380JBetASe0HgQ",
"CAACAgUAAxkBAAKV2me_HEpT3JOOUzFYXEx60jHrS1SKAAKtEQACgNnwV69z3WlbOQegHgQ",
"CAACAgQAAxkBAAKV62e_HSAOCrZl91ePlp-ycQWJXSNAAALYFgACpvFxHj74GKD3lBVqHgQ",
"CAACAgQAAxkBAAKV6me_HRbgSn9-ggtXybOk2ttI_LCXAAIYCQACQ_8RUpOq_3qBgteUHgQ",
"CAACAgQAAxkBAAKV6We_HRQoxwv5PwHe6EFISSLODrzjAAK9FgACpvFxHqjYRWoNyxh4HgQ",
]



